import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between gap-4 border-b border-border px-6 py-3">
          <nav className="flex items-center gap-4 text-sm font-medium">
            <Link href="/checklist" className="hover:underline">
              Client
            </Link>
            <Link href="/admin" className="hover:underline">
              Admin
            </Link>
            <Link href="/rcic" className="hover:underline">
              RCIC
            </Link>
          </nav>
          <span className="text-xs text-muted-foreground">
            Demo only — not real login
          </span>
        </header>
        {children}
      </body>
    </html>
  );
}
