import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { AuthProvider } from "@/lib/firebase/auth-context.tsx";
import { AuthStatus } from "@/components/auth-status.tsx";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <header className="flex items-center justify-between gap-4 border-b border-border px-6 py-3">
            <Link href="/checklist" className="text-sm font-medium hover:underline">
              StayinCanada (sandbox)
            </Link>
            <AuthStatus />
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
